# Generated by Django 2.2.12 on 2022-01-19 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbrbic',
            fields=[
                ('idrbic', models.AutoField(db_column='idrbod', primary_key=True, serialize=False)),
                ('diatra', models.TextField(db_column='diatra', verbose_name='Dia de Transaccion')),
                ('desctra', models.TextField(db_column='desctra', verbose_name='Descripcion de la transaccion')),
                ('codtra', models.TextField(db_column='codtra', verbose_name='Codigo de la transaccion')),
                ('reftra', models.TextField(db_column='reftra', verbose_name='Referencia de la transaccion')),
                ('debe', models.TextField(db_column='debe')),
                ('haber', models.TextField(db_column='haber')),
                ('saldo', models.TextField(db_column='saldo')),
                ('fechact', models.DateTimeField(blank=True, db_column='fechact', null=True, verbose_name='Fecha de carga')),
                ('idusu', models.CharField(db_column='idusu', max_length=16, null=True, verbose_name='Usuario')),
                ('idrenc', models.ForeignKey(db_column='idrenc', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.Cbrenc')),
            ],
            options={
                'db_table': 'cbrbic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cbrbice',
            fields=[
                ('idrbice', models.AutoField(db_column='idrbice', primary_key=True, serialize=False)),
                ('coderr', models.SmallIntegerField(db_column='coderr', default=0)),
                ('idrbic', models.ForeignKey(db_column='idrbic', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.Cbrbic')),
            ],
            options={
                'db_table': 'cbrbice',
                'managed': True,
            },
        ),
    ]
