# Generated by Django 3.2.6 on 2021-09-17 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbsres',
            old_name='linkconciliadoerp',
            new_name='idrerpdl',
        ),
        migrations.RenameField(
            model_name='cbwres',
            old_name='linkconciliadoerp',
            new_name='idrerpdl',
        ),
    ]
