# Generated by Django 3.2.6 on 2021-10-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtusu',
            name='actpas',
            field=models.CharField(blank=True, db_column='actpas', max_length=1, verbose_name='Activo o Pasivo'),
        ),
        migrations.AlterField(
            model_name='cbtusu',
            name='tipousu',
            field=models.CharField(blank=True, db_column='tipousu', default='', max_length=1, verbose_name='Tipo de usuario'),
            preserve_default=False,
        ),
    ]
