# Generated by Django 2.2.12 on 2022-01-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0002_cbrbic_cbrbice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbrban',
            fields=[
                ('idrban', models.AutoField(db_column='idrban', primary_key=True, serialize=False)),
                ('fechatra', models.TextField(db_column='fechatra', verbose_name='Fecha de Transaccion')),
                ('desctra', models.TextField(db_column='desctra', verbose_name='Descripcion de la transaccion')),
                ('reftra', models.TextField(db_column='reftra', verbose_name='Referencia de la transaccion')),
                ('monto', models.TextField(db_column='monto')),
                ('saldo', models.TextField(db_column='saldo')),
                ('fechact', models.DateTimeField(blank=True, db_column='fechact', null=True, verbose_name='Fecha de carga')),
                ('idusu', models.CharField(db_column='idusu', max_length=16, null=True, verbose_name='Usuario de archivo ERP')),
                ('idrenc', models.ForeignKey(db_column='idrenc', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.Cbrenc')),
            ],
            options={
                'db_table': 'cbrban',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cbrbane',
            fields=[
                ('idrbane', models.AutoField(db_column='idrbane', primary_key=True, serialize=False)),
                ('coderr', models.SmallIntegerField(db_column='coderr', default=0)),
                ('idrban', models.ForeignKey(db_column='idrban', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.Cbrban')),
            ],
            options={
                'db_table': 'cbrbane',
                'managed': True,
            },
        ),
    ]
