# Generated by Django 3.2.6 on 2021-09-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0002_auto_20210917_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsresc',
            name='idsresc',
            field=models.AutoField(db_column='idsresc', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
