# Generated by Django 3.2.3 on 2021-07-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0002_cbrbod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrbod',
            name='idrenc',
            field=models.ForeignKey(db_column='idrenc', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbrenc'),
        ),
    ]
