# Generated by Django 3.2.6 on 2021-09-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0003_alter_cbsresc_idsresc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbsresc',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='cbsresc',
            table='cbsresc',
        ),
    ]
