# Generated by Django 2.2.12 on 2022-01-22 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0003_cbrban_cbrbane'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbrbnc',
            fields=[
                ('idrbnc', models.AutoField(db_column='idrbnc', primary_key=True, serialize=False)),
                ('fechatra', models.TextField(db_column='fechatra', verbose_name='Fecha de Transaccion')),
                ('desctra', models.TextField(db_column='desctra', verbose_name='Descripcion de la transaccion')),
                ('reftra', models.TextField(db_column='reftra', verbose_name='Referencia de la transaccion')),
                ('debe', models.TextField(db_column='debe')),
                ('haber', models.TextField(db_column='haber')),
                ('saldo', models.TextField(db_column='saldo')),
                ('fechact', models.DateTimeField(blank=True, db_column='fechact', null=True, verbose_name='Fecha de carga')),
                ('idusu', models.CharField(db_column='idusu', max_length=16, null=True, verbose_name='Usuario de archivo ERP')),
                ('idrenc', models.ForeignKey(db_column='idrenc', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.Cbrenc')),
            ],
            options={
                'db_table': 'cbrbnc',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cbrbnce',
            fields=[
                ('idrbnce', models.AutoField(db_column='idrbnce', primary_key=True, serialize=False)),
                ('coderr', models.SmallIntegerField(db_column='coderr', default=0)),
                ('idrbnc', models.ForeignKey(db_column='idrbnc', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.Cbrbnc')),
            ],
            options={
                'db_table': 'cbrbnce',
                'managed': True,
            },
        ),
    ]
