# Generated by Django 3.2.3 on 2021-07-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0004_auto_20210727_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbterr',
            name='fechact',
            field=models.DateTimeField(blank=True, db_column='fechact', null=True, verbose_name='Fecha de carga'),
        ),
    ]
