# Generated by Django 2.2.12 on 2022-01-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0004_cbrbnc_cbrbnce'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtcli',
            name='husohor',
            field=models.CharField(db_column='husohor', default='00:00', max_length=6, verbose_name='Huso horario'),
        ),
    ]
