# Generated by Django 3.2.6 on 2021-09-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0004_auto_20210917_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrbod',
            name='idrbod',
            field=models.AutoField(db_column='idrbod', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='idrgal',
            field=models.AutoField(db_column='idrgal', primary_key=True, serialize=False),
        ),
    ]
