# Generated by Django 3.2.3 on 2021-07-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0005_alter_cbterr_fechact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrgal',
            name='fechacon',
            field=models.DateField(blank=True, db_column='fechacon', null=True, verbose_name='Fecha de contabilizacion'),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='fechact',
            field=models.DateField(blank=True, db_column='fechact', null=True, verbose_name='Fecha de carga'),
        ),
    ]
