# Generated by Django 2.2.12 on 2022-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0005_cbtcli_husohor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrbic',
            name='idrbic',
            field=models.AutoField(db_column='idrbic', primary_key=True, serialize=False),
        ),
    ]
