# Generated by Django 3.2.3 on 2021-07-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0006_auto_20210728_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsres',
            name='nrocomperp',
            field=models.TextField(blank=True, db_column='nrocomperp', null=True),
        ),
        migrations.AlterField(
            model_name='cbwres',
            name='nrocomperp',
            field=models.TextField(blank=True, db_column='nrocomperp', null=True),
        ),
    ]
