# Generated by Django 3.2.6 on 2021-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0006_auto_20210825_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrenc',
            name='imgbcoroute',
            field=models.FileField(blank=True, null=True, upload_to='temp', verbose_name='Imagen del Banco'),
        ),
    ]
