# Generated by Django 3.2.3 on 2021-07-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0007_auto_20210728_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsres',
            name='glosaerp',
            field=models.CharField(blank=True, db_column='glosaerp', max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='cbwres',
            name='glosaerp',
            field=models.CharField(blank=True, db_column='glosaerp', max_length=90, null=True),
        ),
    ]
