# Generated by Django 3.2.6 on 2021-08-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0007_alter_cbrenc_imgbcoroute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cbrenci',
        ),
    ]
