# Generated by Django 3.2.3 on 2021-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0008_auto_20210728_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbsres',
            name='glosaerp',
            field=models.TextField(blank=True, db_column='glosaerp', null=True),
        ),
        migrations.AlterField(
            model_name='cbwres',
            name='glosaerp',
            field=models.TextField(blank=True, db_column='glosaerp', null=True),
        ),
    ]
