# Generated by Django 3.2.3 on 2021-07-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0009_auto_20210728_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbsres',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cbsres',
            name='isconciliado',
        ),
        migrations.RemoveField(
            model_name='cbsres',
            name='linkconciliado',
        ),
        migrations.RemoveField(
            model_name='cbsres',
            name='tipoconciliado',
        ),
        migrations.AddField(
            model_name='cbsres',
            name='codtcobco',
            field=models.CharField(blank=True, db_column='codtcobco', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='codtcoerp',
            field=models.CharField(blank=True, db_column='codtcoerp', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='estadobco',
            field=models.SmallIntegerField(db_column='estadobco', null=True, verbose_name='Estado Banco'),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='estadoerp',
            field=models.SmallIntegerField(db_column='estado', null=True, verbose_name='Estado Erp'),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='linkconciliadobco',
            field=models.IntegerField(blank=True, db_column='linkconciliadobco', null=True),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='linkconciliadoerp',
            field=models.IntegerField(blank=True, db_column='linkconciliadoerp', null=True),
        ),
    ]
