# Generated by Django 3.2.3 on 2021-07-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0010_auto_20210728_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cbsres',
            old_name='codtrabco',
            new_name='codtra',
        ),
        migrations.RemoveField(
            model_name='cbsres',
            name='desctrabco',
        ),
        migrations.RemoveField(
            model_name='cbsres',
            name='oficinabco',
        ),
        migrations.RemoveField(
            model_name='cbsres',
            name='reftrabco',
        ),
        migrations.AddField(
            model_name='cbsres',
            name='desctra',
            field=models.CharField(blank=True, db_column='desctra', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='oficina',
            field=models.CharField(blank=True, db_column='oficina', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cbsres',
            name='reftra',
            field=models.CharField(blank=True, db_column='reftra', max_length=30, null=True),
        ),
    ]
