# Generated by Django 3.2.3 on 2021-07-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0011_auto_20210728_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbwres',
            name='codtrabco',
        ),
        migrations.AddField(
            model_name='cbwres',
            name='codtra',
            field=models.CharField(blank=True, db_column='codtra', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cbsres',
            name='codtra',
            field=models.CharField(blank=True, db_column='codtra', max_length=30, null=True),
        ),
    ]
