# Generated by Django 3.2.3 on 2021-07-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0012_auto_20210729_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbwres',
            name='desctrabco',
        ),
        migrations.RemoveField(
            model_name='cbwres',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cbwres',
            name='isconciliado',
        ),
        migrations.RemoveField(
            model_name='cbwres',
            name='linkconciliado',
        ),
        migrations.RemoveField(
            model_name='cbwres',
            name='oficinabco',
        ),
        migrations.RemoveField(
            model_name='cbwres',
            name='reftrabco',
        ),
        migrations.RemoveField(
            model_name='cbwres',
            name='tipoconciliado',
        ),
        migrations.AddField(
            model_name='cbwres',
            name='codtcobco',
            field=models.CharField(blank=True, db_column='codtcobco', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='codtcoerp',
            field=models.CharField(blank=True, db_column='codtcoerp', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='desctra',
            field=models.CharField(blank=True, db_column='desctra', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='estadobco',
            field=models.SmallIntegerField(db_column='estadobco', null=True, verbose_name='Estado Banco'),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='estadoerp',
            field=models.SmallIntegerField(db_column='estado', null=True, verbose_name='Estado Erp'),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='linkconciliadobco',
            field=models.IntegerField(blank=True, db_column='linkconciliadobco', null=True),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='linkconciliadoerp',
            field=models.IntegerField(blank=True, db_column='linkconciliadoerp', null=True),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='oficina',
            field=models.CharField(blank=True, db_column='oficina', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cbwres',
            name='reftra',
            field=models.CharField(blank=True, db_column='reftra', max_length=30, null=True),
        ),
    ]
