# Generated by Django 3.2.3 on 2021-08-08 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0013_auto_20210731_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbterr',
            name='tabla',
        ),
        migrations.AddField(
            model_name='cbterr',
            name='descerr',
            field=models.CharField(db_column='tabla', default='as', max_length=30, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cbrgale',
            fields=[
                ('idrgale', models.AutoField(db_column='idrgale', primary_key=True, serialize=False)),
                ('coderr', models.ForeignKey(db_column='coderr', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbterr')),
                ('idrgal', models.ForeignKey(db_column='idrgal', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbrgal')),
            ],
            options={
                'db_table': 'cbrgale',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cbrbode',
            fields=[
                ('idrbode', models.AutoField(db_column='idrbode', primary_key=True, serialize=False)),
                ('coderr', models.ForeignKey(db_column='coderr', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbterr')),
                ('idrbod', models.ForeignKey(db_column='idrbod', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbrgal')),
            ],
            options={
                'db_table': 'cbrbode',
                'managed': True,
            },
        ),
    ]
