# Generated by Django 3.2.3 on 2021-08-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0014_auto_20210808_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrbode',
            name='idrbod',
            field=models.ForeignKey(db_column='idrbod', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbrbod'),
        ),
    ]
