# Generated by Django 3.2.3 on 2021-08-09 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0015_alter_cbrbode_idrbod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbrbode',
            name='coderr',
        ),
        migrations.RemoveField(
            model_name='cbterr',
            name='coderr',
        ),
        migrations.AddField(
            model_name='cbrbode',
            name='idterr',
            field=models.ForeignKey(db_column='idterr', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbterr'),
        ),
        migrations.AlterField(
            model_name='cbterr',
            name='idterr',
            field=models.IntegerField(db_column='idterr', primary_key=True, serialize=False),
        ),
    ]
