# Generated by Django 3.2.3 on 2021-08-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0016_auto_20210808_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbterr',
            name='descerr',
            field=models.CharField(db_column='descerr', max_length=30, verbose_name='Descripcion'),
        ),
    ]
