# Generated by Django 3.2.3 on 2021-08-09 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0017_alter_cbterr_descerr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbrgale',
            name='coderr',
        ),
        migrations.AddField(
            model_name='cbrgale',
            name='idterr',
            field=models.ForeignKey(db_column='idterr', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbterr'),
        ),
    ]
