# Generated by Django 3.2.3 on 2021-08-10 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0018_auto_20210809_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrbode',
            name='idrbod',
            field=models.ForeignKey(db_column='idrbod', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbrbod'),
        ),
        migrations.AlterField(
            model_name='cbrgale',
            name='idrgal',
            field=models.ForeignKey(db_column='idrgal', default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CBR.cbrgal'),
        ),
    ]
