# Generated by Django 3.2.3 on 2021-08-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0019_auto_20210810_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbrbod',
            name='debe',
            field=models.TextField(db_column='debe'),
        ),
        migrations.AlterField(
            model_name='cbrbod',
            name='diatra',
            field=models.TextField(db_column='diatra', verbose_name='Dia de Transaccion'),
        ),
        migrations.AlterField(
            model_name='cbrbod',
            name='haber',
            field=models.TextField(db_column='haber'),
        ),
        migrations.AlterField(
            model_name='cbrbod',
            name='saldo',
            field=models.TextField(db_column='saldo'),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='debe',
            field=models.TextField(db_column='debe'),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='fechacon',
            field=models.TextField(blank=True, db_column='fechacon', null=True, verbose_name='Fecha de contabilizacion'),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='fechatra',
            field=models.TextField(blank=True, db_column='fechatra', null=True),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='haber',
            field=models.TextField(db_column='haber'),
        ),
        migrations.AlterField(
            model_name='cbrgal',
            name='saldo',
            field=models.TextField(db_column='saldo'),
        ),
    ]
