# Generated by Django 3.2.6 on 2021-08-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CBR', '0021_auto_20210822_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbttco',
            name='masmenos',
        ),
        migrations.RemoveField(
            model_name='cbttco',
            name='ordencb010',
        ),
        migrations.AddField(
            model_name='cbttco',
            name='erpbco',
            field=models.SmallIntegerField(blank=True, db_column='erpbco', null=True),
        ),
        migrations.AddField(
            model_name='cbttco',
            name='inddebhab',
            field=models.CharField(blank=True, db_column='inddebhab', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='cbttco',
            name='indsuma',
            field=models.SmallIntegerField(blank=True, db_column='indsuma', null=True),
        ),
        migrations.AddField(
            model_name='cbttco',
            name='ordtco',
            field=models.SmallIntegerField(blank=True, db_column='ordtco', null=True),
        ),
        migrations.AlterField(
            model_name='cbttco',
            name='destco',
            field=models.CharField(db_column='destco', max_length=30, verbose_name='Descripcion tipo de conciliacion'),
        ),
    ]
